version: '3'

services:
  
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  httpd:
    image: httpd:latest
    container_name: httpd
    ports:
      - "8081:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
    environment:
      JENKINS_OPTS: --prefix=/jenkins

  nodeapp:
    image: your-node-image
    container_name: nodeapp
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: "mongodb://mongodb:27017/your_database"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
  jenkins_data:
